# Generated by Django 4.1.3 on 2022-11-22 02:30

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("full_name", models.CharField(help_text="ФИО", max_length=50)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Project name"),
                ),
                (
                    "description",
                    models.TextField(max_length=400, verbose_name="Description"),
                ),
                (
                    "img",
                    models.ImageField(
                        null=True, upload_to="img/", verbose_name="picture"
                    ),
                ),
                (
                    "apply_date",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 11, 22, 9, 30, 54, 270885),
                        editable=False,
                    ),
                ),
                (
                    "com",
                    models.CharField(
                        default="Этот проект ещё не принят в разработку!",
                        max_length=400,
                        verbose_name="Description",
                    ),
                ),
                (
                    "process_status",
                    models.CharField(
                        blank=True,
                        choices=[("i", "В процессе"), ("d", "Готовый"), ("n", "Новые")],
                        default="n",
                        help_text="Статус",
                        max_length=1,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Project owner",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Категория заявки",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.category",
                        to_field="type",
                    ),
                ),
            ],
            options={
                "ordering": ["apply_date"],
            },
        ),
    ]
