# Generated by Django 4.1.1 on 2022-11-15 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 21, 43, 4, 465636), editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='process_status',
            field=models.CharField(blank=True, choices=[('i', 'В процессе'), ('d', 'Готовые'), ('n', 'Новые')], default='n', help_text='Статус', max_length=1),
        ),
    ]
