# Generated by Django 4.1.3 on 2022-11-22 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="apply_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 22, 9, 32, 11, 103083),
                editable=False,
            ),
        ),
    ]
