# Generated by Django 4.1.3 on 2022-11-22 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_project_apply_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="apply_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 22, 9, 33, 42, 813033),
                editable=False,
            ),
        ),
    ]
