# Generated by Django 3.2.16 on 2022-10-17 02:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Project owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 9, 29, 29, 391318), editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='img/', verbose_name='picture'),
        ),
    ]
