# Generated by Django 3.2.16 on 2022-10-17 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20221017_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 9, 35, 12, 709948), editable=False),
        ),
    ]
