# Generated by Django 3.2.16 on 2022-10-17 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_project_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 9, 35, 39, 544021), editable=False),
        ),
    ]
