# Generated by Django 3.2.16 on 2022-10-17 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20221017_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 10, 44, 11, 193405), editable=False),
        ),
    ]
