# Generated by Django 3.2.16 on 2022-10-28 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_project_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 8, 26, 10, 566465), editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='process_status',
            field=models.CharField(blank=True, choices=[('i', 'In process'), ('d', 'done'), ('n', 'new')], default='n', help_text='Status of project', max_length=1),
        ),
    ]
